version: '3'

services:
  orchestrator:
    build: . 
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "4000:4000"
    command: npm run dev
    env_file: .env.docker
    
    depends_on: 
      - redis
      - mongo
      - rabbitmq  
  
  redis:
    image: redis
  
  mongo:
    image: mongo
  
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"



